# Generated by Django 5.2.9 on 2025-12-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_age_alter_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
