# Generated by Django 3.1.14 on 2026-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
